export const ACTION_TYPES = {
    /*fetchTodos: "fetchTodos",
    addTodo: "addTodo",
    deleteTodo: "deleteTodo",
    updateTodo: "updateTodo",*/
    SET_TRAVELS: "SET_TRAVELS",
    SET_COMMENTS: "SET_COMMENTS",
    SET_LAST_TRAVELS: "SET_LAST_TRAVELS",
    SET_POPULAR_TRAVELS: "SET_POPULAR_TRAVELS",
    SET_NEAR_TRAVELS: "SET_NEAR_TRAVELS",
    SET_OPTIONS_CITIES: "SET_OPTIONS_CITIES",
    SET_MAP_DATA: "SET_MAP_DATA",
    SET_MAP_DATA_ADDRESS: "SET_MAP_DATA_ADDRESS",

    UPDATE_COMMENTS: "UPDATE_COMMENTS",
    SET_FRIENDS: "SET_FRIENDS",
    SET_MESSAGES: "SET_MESSAGES",
    SET_WHERE: "SET_WHERE",
    SET_QUERY: "SET_QUERY",
    SET_TRAVEL: "SET_TRAVEL",
    SET_FILTER_TRAVEL: "SET_FILTER_TRAVEL",
    SET_FILTER_FOR_MAP: "SET_FILTER_FOR_MAP",

    SET_MESSAGES_BETWEEN: "SET_MESSAGES_BETWEEN",
    SET_MESSAGES_BETWEEN_NEW: "SET_MESSAGES_BETWEEN_NEW",

    SET_USERS_MESSAGES: "SET_USERS_MESSAGES",
    SET_SUBMITING_FORM: "SET_SUBMITING_FORM",
    SET_TRAVEL_ADDRESS_IDS: "SET_TRAVEL_ADDRESS_IDS",

    SET_TRAVEL_ID: "SET_TRAVEL_ID",
    SET_PERPAGE: "SET_PERPAGE",
    SET_LAT: "SET_LAT",
    SET_LNG: "SET_LNG",
    SET_COUNTRIES: "SET_COUNTRIES",
    REMOVE_TRAVEL: "REMOVE_TRAVEL",
};
